springdoc:
  api-docs:
    path: /api-docs # api-docs :주소 host/{path}
    groups:
      enabled: true
  swagger-ui:
    path: /index.html # host/swagger-ui/{path}
    enabled: true
    groups-order: asc  # 정렬순
    tags-sorter: alpha # 알파벳 정렬순
    operations-sorter: alpha # api 알파벳 정렬순
    display-request-duration: true # API time 요청시간 
    doc-expansion: none # 초기 도큐 펼치기 할래말래 (list, full, none)
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
server:
  port: 8000
spring:
  application:
    name: springboot-base-study
  datasource:
    url: jdbc:mysql://localhost:3307/base?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: studydocker1!
  jpa:
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        query.in_clause_parameter_padding: true
        show_sql: true
        format_sql: true